In [88]:
from sklearn.datasets import load_wine

In [89]:
wine = load_wine()

In [90]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [91]:
df=pd.DataFrame(data=wine['data'],columns=wine['feature_names'])

In [92]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 13 columns):
alcohol                         178 non-null float64
malic_acid                      178 non-null float64
ash                             178 non-null float64
alcalinity_of_ash               178 non-null float64
magnesium                       178 non-null float64
total_phenols                   178 non-null float64
flavanoids                      178 non-null float64
nonflavanoid_phenols            178 non-null float64
proanthocyanins                 178 non-null float64
color_intensity                 178 non-null float64
hue                             178 non-null float64
od280/od315_of_diluted_wines    178 non-null float64
proline                         178 non-null float64
dtypes: float64(13)
memory usage: 18.2 KB


In [93]:
df.head(120)

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0      14.23        1.71  2.43               15.6      127.0           2.80   
1      13.20        1.78  2.14               11.2      100.0           2.65   
2      13.16        2.36  2.67               18.6      101.0           2.80   
3      14.37        1.95  2.50               16.8      113.0           3.85   
4      13.24        2.59  2.87               21.0      118.0           2.80   
5      14.20        1.76  2.45               15.2      112.0           3.27   
6      14.39        1.87  2.45               14.6       96.0           2.50   
7      14.06        2.15  2.61               17.6      121.0           2.60   
8      14.83        1.64  2.17               14.0       97.0           2.80   
9      13.86        1.35  2.27               16.0       98.0           2.98   
10     14.10        2.16  2.30               18.0      105.0           2.95   
11     14.12        1.48  2.32               16.8       95.0           2.20   
12     13.75        1.73  2.41               16.0       89.0           2.60   
13     14.75        1.73  2.39               11.4       91.0           3.10   
14     14.38        1.87  2.38               12.0      102.0           3.30   
15     13.63        1.81  2.70               17.2      112.0           2.85   
16     14.30        1.92  2.72               20.0      120.0           2.80   
17     13.83        1.57  2.62               20.0      115.0           2.95   
18     14.19        1.59  2.48               16.5      108.0           3.30   
19     13.64        3.10  2.56               15.2      116.0           2.70   
20     14.06        1.63  2.28               16.0      126.0           3.00   
21     12.93        3.80  2.65               18.6      102.0           2.41   
22     13.71        1.86  2.36               16.6      101.0           2.61   
23     12.85        1.60  2.52               17.8       95.0           2.48   
24     13.50        1.81  2.61               20.0       96.0           2.53   
25     13.05        2.05  3.22               25.0      124.0           2.63   
26     13.39        1.77  2.62               16.1       93.0           2.85   
27     13.30        1.72  2.14               17.0       94.0           2.40   
28     13.87        1.90  2.80               19.4      107.0           2.95   
29     14.02        1.68  2.21               16.0       96.0           2.65   
..       ...         ...   ...                ...        ...            ...   
90     12.08        1.83  2.32               18.5       81.0           1.60   
91     12.00        1.51  2.42               22.0       86.0           1.45   
92     12.69        1.53  2.26               20.7       80.0           1.38   
93     12.29        2.83  2.22               18.0       88.0           2.45   
94     11.62        1.99  2.28               18.0       98.0           3.02   
95     12.47        1.52  2.20               19.0      162.0           2.50   
96     11.81        2.12  2.74               21.5      134.0           1.60   
97     12.29        1.41  1.98               16.0       85.0           2.55   
98     12.37        1.07  2.10               18.5       88.0           3.52   
99     12.29        3.17  2.21               18.0       88.0           2.85   
100    12.08        2.08  1.70               17.5       97.0           2.23   
101    12.60        1.34  1.90               18.5       88.0           1.45   
102    12.34        2.45  2.46               21.0       98.0           2.56   
103    11.82        1.72  1.88               19.5       86.0           2.50   
104    12.51        1.73  1.98               20.5       85.0           2.20   
105    12.42        2.55  2.27               22.0       90.0           1.68   
106    12.25        1.73  2.12               19.0       80.0           1.65   
107    12.72        1.75  2.28               22.5       84.0           1.38   
108    12.22        1.29  1.94               19.0      

In [94]:
df['target']=wine['target']

In [95]:
df['target']

0      0
1      0
2      0
3      0
4      0
5      0
6      0
7      0
8      0
9      0
10     0
11     0
12     0
13     0
14     0
15     0
16     0
17     0
18     0
19     0
20     0
21     0
22     0
23     0
24     0
25     0
26     0
27     0
28     0
29     0
      ..
148    2
149    2
150    2
151    2
152    2
153    2
154    2
155    2
156    2
157    2
158    2
159    2
160    2
161    2
162    2
163    2
164    2
165    2
166    2
167    2
168    2
169    2
170    2
171    2
172    2
173    2
174    2
175    2
176    2
177    2
Name: target, Length: 178, dtype: int32

In [96]:
X=df.drop('target',axis=1)
y=df['target']

In [97]:
from sklearn.preprocessing import StandardScaler

In [98]:
ss= StandardScaler()
scaled_array=ss.fit_transform(X)
X= pd.DataFrame(data=scaled_array,columns=X.columns)

In [99]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.33)

In [100]:
from sklearn.naive_bayes import GaussianNB

In [101]:
model=GaussianNB()

In [102]:
model.fit(X_train,y_train)

GaussianNB(priors=None)

In [103]:
ypred=model.predict(X_test)

In [104]:
from sklearn.metrics import confusion_matrix

In [105]:
confusion_matrix(y_test,ypred)

array([[20,  0,  0],
       [ 1, 19,  1],
       [ 0,  0, 18]], dtype=int64)

In [106]:
from sklearn.tree import DecisionTreeClassifier #decision tree algorithm started

In [107]:
model=DecisionTreeClassifier()

In [108]:
model.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [109]:
ypred=model.predict(X_test)

In [110]:
from sklearn.metrics  import confusion_matrix

In [111]:
confusion_matrix(y_test,ypred)

array([[20,  0,  0],
       [ 1, 17,  3],
       [ 0,  0, 18]], dtype=int64)

In [112]:
from sklearn.ensemble import RandomForestClassifier

In [115]:
model=RandomForestClassifier()

In [116]:
model.fit(X_train,y_train)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [117]:
ypred=model.predict(X_test)

In [121]:
from sklearn.metrics import confusion_matrix

In [123]:
confusion_matrix(y_test,ypred)

array([[20,  0,  0],
       [ 0, 19,  2],
       [ 0,  2, 16]], dtype=int64)