In [3]:
import numpy as np

In [5]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(0,10,2
         )

array([0, 2, 4, 6, 8])

In [7]:
np.zeros(3
        )

array([0., 0., 0.])

In [12]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [32]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [31]:
np.linspace(0,12,60)

array([ 0.        ,  0.20338983,  0.40677966,  0.61016949,  0.81355932,
        1.01694915,  1.22033898,  1.42372881,  1.62711864,  1.83050847,
        2.03389831,  2.23728814,  2.44067797,  2.6440678 ,  2.84745763,
        3.05084746,  3.25423729,  3.45762712,  3.66101695,  3.86440678,
        4.06779661,  4.27118644,  4.47457627,  4.6779661 ,  4.88135593,
        5.08474576,  5.28813559,  5.49152542,  5.69491525,  5.89830508,
        6.10169492,  6.30508475,  6.50847458,  6.71186441,  6.91525424,
        7.11864407,  7.3220339 ,  7.52542373,  7.72881356,  7.93220339,
        8.13559322,  8.33898305,  8.54237288,  8.74576271,  8.94915254,
        9.15254237,  9.3559322 ,  9.55932203,  9.76271186,  9.96610169,
       10.16949153, 10.37288136, 10.57627119, 10.77966102, 10.98305085,
       11.18644068, 11.38983051, 11.59322034, 11.79661017, 12.        ])

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
np.eye(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [17]:
np.random.rand(3
              )

array([0.06855482, 0.89161522, 0.67618053])

In [21]:
np.random.rand(4,5)

array([[0.15140334, 0.68816996, 0.34425157, 0.86585024, 0.9337514 ],
       [0.39644959, 0.39634223, 0.26229317, 0.47123805, 0.04470951],
       [0.61941031, 0.11802026, 0.00323214, 0.21391707, 0.20779006],
       [0.62461823, 0.75307817, 0.5610448 , 0.50526821, 0.09085394]])

In [22]:
np.random.randint(4)

1

In [26]:
np.random.randint(1,50
                 )

15

In [29]:
np.random.randint(1,50,10)

array([49, 10, 35, 16, 24,  6, 23, 14, 11, 30])

In [33]:
arr= np.arange(0,25)

In [34]:
ranarr=np.random.randint(0,50,10)

In [35]:
ranarr

array([47, 46, 35, 15, 27, 48, 37,  2, 40, 43])

In [36]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [39]:
arr.shape

(25,)

In [40]:
arr.reshape(25,)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [41]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [42]:
arr.max()

24

In [43]:
arr.argmax()

24

In [44]:
arr.argmin()

0